spring:
  application:
    name: appointment-backend
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123.com
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 123456789123456789123456789123456789123456789123456789123456789123456789
  expiration: 86400000